### ISSUE TITLE
Load from modlist.txt files when dll is attached, not when dx9 device is created

### ISSUE THREAD

**Issue by 3vcloud** [gwdevhub/gMod#28]
Theres a potential bug in gwlauncher that means that the modlist.txt thats created could be overwritten before gmod can access it (I've not committed the gwlauncher code yet because of this). The solution is to read the modlist file(s) from disk when gmod is launched rather than when the dx9 device is created.

Once the dll has read the info, we can be free to do whatever we want with the modlist file on disk (i.e. rewrite the contents for the next queued gw account in gwlauncher)

Not so much a bug but not a new feature either

**Comment by DubbleClick** [comment]
fixed in #30
