### ISSUE TITLE
Optimize archive loading

### ISSUE THREAD

**Issue by AlexMacocian** [gwdevhub/gMod#4]
When loading zips or tpfs, gMod first loads a buffer of the file in memory (using a stream). Then it reads and copies the entire stream in memory. Then, it unzips each entry in memory in its own buffer. Finally, it copies the entire zipped buffers into another buffer. 

Ideally this should all be reduced to at most one buffer.

**Comment by AlexMacocian** [comment]
https://github.com/zlib-ng/minizip-ng

**Comment by DubbleClick** [comment]
I started with miniz but found libzippp (libzip with c++ bindings).

**Comment by AlexMacocian** [comment]
We can probably close this @DubbleClick
